name: SimpleFly
version: '${project.version}'
main: simplexity.simplefly.SimpleFly
api-version: '1.20'
commands:
  fly:
    permission: simplefly.fly
    description: allows toggling flight
    usage: /fly <player>
    aliases: [sfly]
    permission-message: You don't have permission to use this command.
  flyspeed:
    permission: simplefly.flyspeed
    description: allows changing fly speed
    usage: /flyspeed [set|reset] <player> <speed>
    aliases: [sflyspeed]
    permission-message: You don't have permission to use this command.
  flyreload:
    permission: simplefly.reload
    description: reloads the plugin
    aliases: [sflyreload]
    permission-message: You don't have permission to use this command.
permissions:
  simplefly.fly:
    default: op
    description: allows toggling flight
  simplefly.others.fly:
    default: op
    description: allows toggling flight for others
  simplefly.flyspeed:
    default: op
    description: allows changing fly speed
  simplefly.others.flyspeed:
    default: op
    description: allows changing fly speed for others
  simplefly.reload:
    default: op
    description: allows reloading the plugin


